# Generated by Django 4.0.1 on 2023-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=50)),
                ('uname', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('gender', models.TextField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=100)),
                ('website', models.TextField(max_length=100)),
                ('category', models.TextField(max_length=50)),
            ],
        ),
    ]
