# Generated by Django 4.0.1 on 2023-04-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramgateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
    ]
